server {
    listen 80;

    location / {
        proxy_pass http://nextjs:3000;
    }

    location /api/auth/ {
        proxy_pass http://django:8000;
    }

    location /api/match/ {
        proxy_pass http://fastapi:8001;
    }
}