# Generated by Django 6.0.4 on 2026-04-16 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username_alter_user_is_active_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['token'], name='accounts_au_token_c2b7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user', 'type'], name='accounts_au_user_id_e4f195_idx'),
        ),
    ]
