# Generated by Django 6.0.4 on 2026-05-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeMode', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentverification',
            new_name='collegeMode_user_id_743985_idx',
            old_name='collegeMode_user_id_6d604c_idx',
        ),
        migrations.RenameIndex(
            model_name='studentverification',
            new_name='collegeMode_college_2d0299_idx',
            old_name='collegeMode_college_1b83d3_idx',
        ),
    ]
