# Generated by Django 6.0.4 on 2026-05-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('profiles', '0004_remove_profile_profiles_pr_latitud_6b6a14_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='culturalprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='culturalprofile',
            name='caste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferences.caste'),
        ),
        migrations.CreateModel(
            name='Gotra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gotras', to='preferences.caste')),
            ],
            options={
                'unique_together': {('name', 'caste')},
            },
        ),
        migrations.AlterField(
            model_name='culturalprofile',
            name='gotra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferences.gotra'),
        ),
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castes', to='preferences.religion'),
        ),
        migrations.AlterField(
            model_name='culturalprofile',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferences.religion'),
        ),
        migrations.AlterUniqueTogether(
            name='caste',
            unique_together={('name', 'religion')},
        ),
    ]
