# Generated by Django 6.0.4 on 2026-04-29 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_dob', models.BooleanField(default=False)),
                ('show_profile_image', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('show_profile_views', models.BooleanField(default=True)),
                ('anonymous_viewing', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('blur_profile_image', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='profiles_pr_user_id_7279cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['viewed', '-created_at'], name='profiles_pr_viewed__2461de_idx'), models.Index(fields=['viewer', 'viewed'], name='profiles_pr_viewer__bff7f4_idx')],
                'unique_together': {('viewer', 'viewed')},
            },
        ),
    ]
