# Generated by Django 6.0.4 on 2026-05-04 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_caste_religion_alter_culturalprofile_profile_and_more'),
        ('profiles', '0004_remove_profile_profiles_pr_latitud_6b6a14_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferences.caste'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gotra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferences.gotra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='horoscope',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preferences.religion'),
        ),
    ]
