# Generated by Django 6.0.4 on 2026-05-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_caste_profile_gan_profile_gotra_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profilesettings',
            name='profiles_pr_user_id_7279cc_idx',
        ),
        migrations.DeleteModel(
            name='ProfileSettings',
        ),
    ]
