# Generated by Django 6.0.4 on 2026-05-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profilesettings_profiles_pr_user_id_7279cc_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileview',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='profileview',
            name='profiles_pr_viewed__2461de_idx',
        ),
        migrations.RemoveIndex(
            model_name='profileview',
            name='profiles_pr_viewer__bff7f4_idx',
        ),
        migrations.DeleteModel(
            name='ProfileView',
        ),
    ]
