# Generated by Django 6.0.4 on 2026-05-06 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_dob', models.BooleanField(default=False)),
                ('show_profile_image', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('show_profile_views', models.BooleanField(default=True)),
                ('anonymous_viewing', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('blur_profile_image', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='settings_pr_user_id_e2e334_idx')],
            },
        ),
    ]
